package com.tachisatok.notelesson.constant

/**
 * 出題する音階の範囲を管理するEnum
 *
 * @property character よみがな
 * @property scaleList 音階リスト
 */
enum class ScaleRange(
    private val character: Character,
    private val scaleList: List<Scale>
) {
    // LEVEL1
    G_CLEF_OCTAVE4_C_TO_OCTAVE4_E(
        Character.C_TO_E,
        listOf(
            Scale.G_CLEF_OCTAVE4_C,
            Scale.G_CLEF_OCTAVE4_D,
            Scale.G_CLEF_OCTAVE4_E
        )
    ),
    G_CLEF_OCTAVE4_C_TO_OCTAVE4_G(
        Character.C_TO_G,
        listOf(
            Scale.G_CLEF_OCTAVE4_C,
            Scale.G_CLEF_OCTAVE4_D,
            Scale.G_CLEF_OCTAVE4_E,
            Scale.G_CLEF_OCTAVE4_F,
            Scale.G_CLEF_OCTAVE4_G
        )
    ),
    G_CLEF_OCTAVE4_C_TO_OCTAVE5_C(
        Character.C_TO_C,
        listOf(
            Scale.G_CLEF_OCTAVE4_C,
            Scale.G_CLEF_OCTAVE4_D,
            Scale.G_CLEF_OCTAVE4_E,
            Scale.G_CLEF_OCTAVE4_F,
            Scale.G_CLEF_OCTAVE4_G,
            Scale.G_CLEF_OCTAVE4_A,
            Scale.G_CLEF_OCTAVE4_B,
            Scale.G_CLEF_OCTAVE5_C
        )
    ),
    F_CLEF_OCTAVE3_A_TO_OCTAVE4_C(
        Character.A_TO_C,
        listOf(
            Scale.F_CLEF_OCTAVE3_A,
            Scale.F_CLEF_OCTAVE3_B,
            Scale.F_CLEF_OCTAVE4_C
        )
    ),
    F_CLEF_OCTAVE3_F_TO_OCTAVE4_C(
        Character.F_TO_C,
        listOf(
            Scale.F_CLEF_OCTAVE3_F,
            Scale.F_CLEF_OCTAVE3_G,
            Scale.F_CLEF_OCTAVE3_A,
            Scale.F_CLEF_OCTAVE3_B,
            Scale.F_CLEF_OCTAVE4_C
        )
    ),
    F_CLEF_OCTAVE3_C_TO_OCTAVE4_C(
        Character.C_TO_C,
        listOf(
            Scale.F_CLEF_OCTAVE3_C,
            Scale.F_CLEF_OCTAVE3_D,
            Scale.F_CLEF_OCTAVE3_E,
            Scale.F_CLEF_OCTAVE3_F,
            Scale.F_CLEF_OCTAVE3_G,
            Scale.F_CLEF_OCTAVE3_A,
            Scale.F_CLEF_OCTAVE3_B,
            Scale.F_CLEF_OCTAVE4_C
        )
    ),

    // LEVEL2
    G_CLEF_OCTAVE5_C_TO_OCTAVE5_E(
        Character.C_TO_E,
        listOf(
            Scale.G_CLEF_OCTAVE5_C,
            Scale.G_CLEF_OCTAVE5_D,
            Scale.G_CLEF_OCTAVE5_E
        )
    ),
    G_CLEF_OCTAVE5_C_TO_OCTAVE5_G(
        Character.C_TO_G,
        listOf(
            Scale.G_CLEF_OCTAVE5_C,
            Scale.G_CLEF_OCTAVE5_D,
            Scale.G_CLEF_OCTAVE5_E,
            Scale.G_CLEF_OCTAVE5_F,
            Scale.G_CLEF_OCTAVE5_G
        )
    ),
    G_CLEF_OCTAVE5_C_TO_OCTAVE6_C(
        Character.C_TO_C,
        listOf(
            Scale.G_CLEF_OCTAVE5_C,
            Scale.G_CLEF_OCTAVE5_D,
            Scale.G_CLEF_OCTAVE5_E,
            Scale.G_CLEF_OCTAVE5_F,
            Scale.G_CLEF_OCTAVE5_G,
            Scale.G_CLEF_OCTAVE5_A,
            Scale.G_CLEF_OCTAVE5_B,
            Scale.G_CLEF_OCTAVE6_C
        )
    ),
    F_CLEF_OCTAVE2_A_TO_OCTAVE3_C(
        Character.A_TO_C,
        listOf(
            Scale.F_CLEF_OCTAVE2_A,
            Scale.F_CLEF_OCTAVE2_B,
            Scale.F_CLEF_OCTAVE3_C
        )
    ),
    F_CLEF_OCTAVE2_F_TO_OCTAVE3_C(
        Character.F_TO_C,
        listOf(
            Scale.F_CLEF_OCTAVE2_F,
            Scale.F_CLEF_OCTAVE2_G,
            Scale.F_CLEF_OCTAVE2_A,
            Scale.F_CLEF_OCTAVE2_B,
            Scale.F_CLEF_OCTAVE3_C
        )
    ),
    F_CLEF_OCTAVE2_C_TO_OCTAVE3_C(
        Character.C_TO_C,
        listOf(
            Scale.F_CLEF_OCTAVE2_C,
            Scale.F_CLEF_OCTAVE2_D,
            Scale.F_CLEF_OCTAVE2_E,
            Scale.F_CLEF_OCTAVE2_F,
            Scale.F_CLEF_OCTAVE2_G,
            Scale.F_CLEF_OCTAVE2_A,
            Scale.F_CLEF_OCTAVE2_B,
            Scale.F_CLEF_OCTAVE3_C
        )
    ),

    // LEVEL3
    G_CLEF_OCTAVE4_C_TO_OCTAVE6_C(
        Character.C_TO_C,
        listOf(
            Scale.G_CLEF_OCTAVE4_C,
            Scale.G_CLEF_OCTAVE4_D,
            Scale.G_CLEF_OCTAVE4_E,
            Scale.G_CLEF_OCTAVE4_F,
            Scale.G_CLEF_OCTAVE4_G,
            Scale.G_CLEF_OCTAVE4_A,
            Scale.G_CLEF_OCTAVE4_B,
            Scale.G_CLEF_OCTAVE5_C,
            Scale.G_CLEF_OCTAVE5_D,
            Scale.G_CLEF_OCTAVE5_E,
            Scale.G_CLEF_OCTAVE5_F,
            Scale.G_CLEF_OCTAVE5_G,
            Scale.G_CLEF_OCTAVE5_A,
            Scale.G_CLEF_OCTAVE5_B,
            Scale.G_CLEF_OCTAVE6_C
        )
    ),
    F_CLEF_OCTAVE2_C_TO_OCTAVE4_C(
        Character.C_TO_C,
        listOf(
            Scale.F_CLEF_OCTAVE2_C,
            Scale.F_CLEF_OCTAVE2_D,
            Scale.F_CLEF_OCTAVE2_E,
            Scale.F_CLEF_OCTAVE2_F,
            Scale.F_CLEF_OCTAVE2_G,
            Scale.F_CLEF_OCTAVE2_A,
            Scale.F_CLEF_OCTAVE2_B,
            Scale.F_CLEF_OCTAVE3_C,
            Scale.F_CLEF_OCTAVE3_D,
            Scale.F_CLEF_OCTAVE3_E,
            Scale.F_CLEF_OCTAVE3_F,
            Scale.F_CLEF_OCTAVE3_G,
            Scale.F_CLEF_OCTAVE3_A,
            Scale.F_CLEF_OCTAVE3_B,
            Scale.F_CLEF_OCTAVE4_C
        )
    ),
}